### PR TITLE
Add new sample for OutputPreview.

### PR DESCRIPTION
**Pull request by datalogics-josepha**
To demonstrate generating an OutputPreview image from a PDF page, this is typically used during Soft Proofing prior to final print.

### CODE REVIEW

**Review by datalogics-saharay — CHANGES_REQUESTED** [review]
The sample looks good! I think the Output Preview sample description needs to be added to the README.md.

**Comment by datalogics-josepha** [comment]
markdown updated*

**Comment by datalogics-saharay** [comment]
> markdown updated*

@datalogics-josepha It doesn't look like the markdown changes are in the PR.

**Comment by datalogics-josepha** [comment]
fixed*

**Review by datalogics-saharay — APPROVED** [review]

**Pull request merged**
